configured_endpoints: 18
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/coolsapiens%2Fbrowserbase-unofficial-cc5f83abcd7a47007ec5bc8af8334f91fa569ba918f7c1fd266d8638eccb0c8e.yml
openapi_spec_hash: 72f5ea0f06adc0f9224d0f1e8c780a87
config_hash: f5f6934b0e449c2dce0d5ec1b8dbf9b2
